---
title:   Java의 예외 처리

subtitle:  TODO
categories: language 
tags: java  exception
 
toc: true
toc_sticky: true
---

  
  
e.getMessage()는 자바가 전달한 인스턴스의 메소드 중 getMessage를 호출하는 코드인데, getMessage는 오류의 원인을 사람이 이해하기 쉬운 형태로 리턴하도록 약속되어 있다.  
  
  
  
  
  
## e.getMessage();  
오류에 대한 기본적인 내용을 출력해준다. 상세하지 않다.  
## e.toString()  
e.toString()을 호출한 결과는 java.lang.ArithmeticException: / by zero 이다. e.toString()은 e.getMessage()보다 더 자세한 예외 정보를 제공한다. java.lang.ArithmeticException은 발생한 예외가 어떤 예외에 해당하는지에 대한 정보라고 지금을 생각하자. ArithmeticException 수학적인 계산의 과정에서 발생하는 예외상황을 의미한다. (우리는 어떤 숫자를 0으로 나누려고 하고 있다는 것을 상기하자)  
## e.printStackTrace()  
메소드 getMessage, toString과는 다르게 printStackTrace는 리턴값이 없다. 이 메소드를 호출하면 메소드가 내부적으로 예외 결과를 화면에 출력한다. printStackTrace는 가장 자세한 예외 정보를 제공한다.  
  
  
  
  
  
위의 코드를 컴파일해보면 아래와 같은 에러가 발생하면서 컴파일이 되지 않을 것이다.  
1  
2  
3  
4  
5  
Exception in thread "main" java.lang.Error: Unresolved compilation problems:   
    Unhandled exception type FileNotFoundException  
    Unhandled exception type IOException  
   
    at org.opentutorials.javatutorials.exception.CheckedExceptionDemo.main(CheckedExceptionDemo.java:5)  
 우선 아래의 오류를 살펴보자.  
Unhandled exception type FileNotFoundException  
이것은 아래 로직에 대한 예외처리가 필요하다는 뜻이다.  
  
  
내가 처리못하니 던질건데 그러니까 쓴는쪽은 트라이가 있어야해ㅜ안그러면 컴파일에러 날거야  
  
  
  
  
지금까지 예외를 처리하는 방법으로 try…catch…finally를 배웠다. 이외에 다른 방법도 있다.  throw를 사용하는 것이다. throw는 예외처리를 다음 사용자에게 넘기는 것이다. 다음 사용자는 누구일까? 코드를 보자.  
1  
2  
3  
4  
5  
6  
7  
8  
9  
10  
11  
12  
13  
14  
15  
16  
17  
18  
**package** org.opentutorials.javatutorials.exception;  
   
**class** B{  
    **void** run(){  
    }  
}  
**class** C{  
    **void** run(){  
        B b = **new** B();  
        b.run();  
    }  
}  
**public** **class** ThrowExceptionDemo {  
    **public** **static** **void** main(String[] args) {  
         C c = **new** C();  
         c.run();  
    }     
}  
ThrowExceptionDemo.main(클래스 ThrowExceptionDem의 메소드 main)은 C.run의 사용자이다. C.run은 B.run의 사용자이다. 반대로 B.run의 다음 사용자는 C.run이고 C.run의 다음 사용자는 ThrowExceptionDem.main이 되는 셈이다. 파일을 읽은 로직을 추가해보자.  
  
  
  
  
주목할 차이점은 아래와 같다.  
![]({{ site.url }}{{ site.baseurl }}/assets/images/37e8737fc69ebf4b9f17d469f94f5b16/2076.png)  
B 내부의 try…catch 구문은 제거되었고 run 옆에 throws IOException, FileNotFoundException이 추가되었다. 이것은 B.run 내부에서 IOException, FileNotFoundException에 해당하는 예외가 발생하면 이에 대한 처리를 B.run의 사용자에게 위임하는 것이다. 위의 코드에서 B.run의 사용자는 C.run이다. 따라서 C.run은 아래와 같이 수정돼야 한다.  
  
  
  
  
예외 처리는 귀찮은 일이다. 그래서 예외를 다음 사용자에게 전가(throw)하거나 try…catch로 감싸고 아무것도 하지 않고 싶은 유혹에 빠지기 쉽다. 하지만 예외는 API를 사용하면서 발생할 수 있는 잠재적 위협에 대한 API 개발자의 강력한 암시다. 이 암시를 무시해서는 안 된다. 물론 더욱 고민스러운 것은 예외 처리 방법에 정답이 없다는 것이겠지만 말이다.  
  
  
  
다음은 기억할만한 주요 Exception들의 리스트다. ( [effective Java p338 참고](http://book.daum.net/detail/book.do?bookid=KOR9788986044768) )  
예외  
사용해야 할 상황  
IllegalArgumentException  
매개변수가 의도하지 않은 상황을 유발시킬 때  
IllegalStateException  
메소드를 호출하기 위한 상태가 아닐 때  
NullPointerException  
매개 변수 값이 null 일 때  
IndexOutOfBoundsException  
인덱스 매개 변수 값이 범위를 벗어날 때  
ArithmeticException  
산술적인 연산에 오류가 있을  
  
  
  
  
## 이번엔 아래와 같이 코드를 바꿔보자.  
1  
2  
3  
4  
5  
6  
7  
8  
9  
10  
**package** org.opentutorials.javatutorials.exception;  
**import** java.io.IOException;  
**class** E{  
    **void** throwArithmeticException(){  
        **throw** **new** ArithmeticException();  
    }  
    **void** throwIOException(){  
        **throw** **new** IOException();  
    }  
}  
  
  
  
  
에러에는 아래와 같이 적혀있다.  
unreported exception IOException; must be caught or declared to be thrown  
즉 IOException은 try…catch하거나 throw 해야 한다는 뜻이다.  
이상하다 ArithmeticException, IOException 모두 Exception이다. 그럼에도 불구하고 유독 IOException만 try…catch 혹은 throw 를 해야 한다는 뜻이다. 자바는 이 두개의 예외를 다른 방법으로 대하고 있는 것이다.   
  
  
예제의 핵심은 IOException은 예외처리를 강제하고 있지만 ArithmeticException은 그렇지 않다 점이다. 그 이유를 알아보자.  
## 예외의 선조 - Throwable  
  
## Throwable  
클래스 Throwable은 범 예외 클래스들의 공통된 조상이다. 모든 예외 클래스들이 가지고 있는 공통된 메소드를 정의하고 있다. 중요한 역할을 하는 클래스임에는 틀림없지만 이 클래스를 직접 사용하지는 않기 때문에 우리에게는 중요하지 않다.  
## Error  
에러는 여러분의 애플리케이션의 문제가 아니라 그 애플리케이션이 동작하는 가상머신에 문제가 생겼을 때 발생하는 예외다. 애플리케이션을 구동시키기에는 메모리가 부족한 경우가 이에 속한다. 이런 경우는 애플리케이션 개발자가 할 수 있는 것이 없다. 따라서 예외처리를 하지 말고 그냥 에러로 인해서 애플리케이션이 중단되도록 내버려둔다. 대신 자신의 애플리케이션이 메모리를 과도하게 사용하고 있다면 로직을 변경하거나 자바 가상머신에서 사용하는 메모리의 제한을 변경하는 등의 대응을 한다.  
## Exception  
결국 우리의 관심사는 Exception 클래스와 RuntimeException 클래스로 좁혀진다. 우선  [Exception 클래스의 하위 클래스들의 목록](http://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html) 을 살펴보자. 아래 클래스들은 모두 Exception 클래스를 상속한 예외 클래스다.  
  
  
필자가 강조 표시한 부분을 보자. 저 많은 클래스 중의 하나가 RuntimeException이다. 도대체 RuntimeException 클래스는 어떤 특이점이 있길래 부모 클래스인 Exception 클래스와 함께 언급되는 것일까? RuntimeException을 제외한 Exception 클래스의 하위 클래스들과 RuntimeException 클래스의 차이를 자바에서는 checked와 unckecked라고 부른다. 관계를 정리하면 아래와 같다.  
* checked 예외 - RuntimeException을 제외한 Exception의 하위 클래스  
* unchekced 예외 - RuntimeException의 하위 클래스  
~checked 예외는 반드시 예외처리를 해야 하는 되는 것이고, unchekced는 해도 되고 안 해도 되는 예외다.~ 바로 이 지점이 IOException과 ArithmeticException의 차이점이다. 아래는 두개 클래스들의 가계도를 보여준다.  
  
  
  
강조 표시한 부분을 주의 깊게 살펴보자. ArithmeticException의 부모 중에 RuntimeException이 있다. 반면에 IOException은 Exception의 자식이지만 RuntimeException의 자식은 아니다. 이런 이유로 IOException은 checked이고 ArithmeticException은 unchekced이다. (Error도 unchecked이다  
  
  
  
  
모든 예외의 조상은 java.lang.Exception이다. switch의 default문처럼 마지막 catch는Exception으로선언해서 예외가 빠져나가지 않도록 하자 예외를 빠져나가면 해당 쓰레드가 종료되어버린다. 반대로 제일위에 선언해버리면 무조건 그곳으로만 히트하니 주의하자  
  
  
  
  
  
  
  
표준 예외 클래스로도 많은 예외 상황을 표현할 수 있다. 하지만 그렇지 않은 경우도 있을 것이다. 이런 때는 직접 예외를 만들면 된다.  
예외를 만들기 전에 해야 할 것은 자신의 예외를 checked로 할 것인가? unchecked로 할 것인가를 정해야 한다. 그 기준은 모호한 문제다. 하지만 기준이 없는 것도 아니다.  
API 쪽에서 예외를 던졌을 때 API 사용자 쪽에서 예외 상황을 복구 할 수 있다면 checked 예외를 사용한다. checked 예외는 사용자에게 문제를 해결할 기회를 주는 것이면서 예외처리를 강제하는 것이다. 하지만 checked 예외를 너무 자주 사용하면 API 사용자를 몹시 힘들게 할 수 있기 때문에 적정선을 찾는 것이 중요하다.  
사용자가 API의 사용방법을 어겨서 발생하는 문제거나 예외 상황이 이미 발생한 시점에서 그냥 프로그램을 종료하는 것이 덜 위험 할 때 unchecked를 사용한다.   
  
  
  
  
